/* ============================================================
   Family Tree — sample dataset
   A fictional multi-generational family (the Adler family),
   spanning ~1903 → present, with English + Hebrew names.
   Demonstrates: remarriage, half-siblings, step-parents,
   partnerships (unmarried), surname changes, side-links,
   personal milestones, birth/marriage/death events.
   ============================================================ */
(function () {
  // Sex: 'm' | 'f'. living derived from deathYear == null.
  // gen: generation row (0 = oldest). Spouses-in share partner's gen.
  const people = [
    // ---- Gen 0 — founders ----
    { id: 'yosef',  gen: 0, sex: 'm', name: { en: 'Yosef Adler',   he: 'יוֹסֵף אַדְלֶר' },
      names: { birth: { en: 'Yosef Adlerstein', he: 'יוֹסֵף אַדְלֶרְשְׁטַיְן' } },
      nameChange: { year: 1934, kind: 'immigration', from: 'Adlerstein', to: 'Adler',
        note: 'Shortened the family name from Adlerstein to Adler at the Haifa immigration desk — “shorter for a shop sign,” he said.' },
      birth: { year: 1903, place: 'Vilnius, Lithuania' }, death: { year: 1979, place: 'Haifa, Israel' },
      parents: [], milestones: [
        { year: 1904, he: 'דיוקן ראשון, על ברכי אמו', postHe: 'עוד לא בן שנה, מוּשב זקוף על ברכי אמו אצל הצלם בווילנה — עיניים פעורות אל מנורת הבזק, בשמלת טבילה לבנה שכבר שירתה שני בני דודים.', en: 'First portrait, on his mother’s lap', tier: 'minor', post: 'Not yet a year old, propped upright on his mother’s lap for the photographer in Vilnius — wide-eyed at the flash lamp, in a christening-white gown that had already served two cousins.' },
        { year: 1911, he: 'ימי בית הספר בווילנה', postHe: 'בן שמונה בכובע בית הספר, יד אחת מונחת על ספרי הצלם כאילו היו שלו. קרא כל מה שהגיע לידיו — בעיקר על מכונות.', en: 'School days in Vilnius', tier: 'minor', post: 'Eight years old in his school cap, one hand resting on the photographer’s books as if they were his own. He read everything he could get — mostly about machines.' },
        { year: 1919, he: 'בן שש עשרה, בחליפה הראשונה', postHe: 'החליפה הראשונה שלו, מצולמת בלי שום אירוע שמישהו זוכר. המצח הרציני לא עזב אותו מעולם.', en: 'Sixteen, in his first suit', tier: 'minor', post: 'His first proper suit, photographed for no occasion anyone remembers. The serious brow never left him.' },
        { year: 1925, he: 'למד שענוּת', postHe: 'שלוש שנים שוליה אצל מר לינדורף הזקן ברחוב נימיצקה, לומד לנקות מנגנון בעיניים עצומות, במישוש בלבד. לינדורף עקב אחרי כל תנועה מעבר לשולחן — הלוח הזה צולם בסדנה, באמצע תיקון.', en: 'Trained as a watchmaker', tier: 'minor', post: 'Apprenticed for three years to old Mr. Lindorff on Niemiecka Street, learning to clean a movement blind, by feel alone. Lindorff watched every move from across the bench — this plate was taken in the workshop, mid-repair.' },
        { year: 1934, he: 'עלה לארץ ישראל', postHe: 'עזב את וילנה עם מזוודה אחת, כלי העבודה ושעון הכיס מפליז שנשא אביו. צולם על הרציף בחיפה בבוקר שבו ירד לחוף — המזוודה וארגז הכלים לרגליו הם כל רכושו. השעון עדיין מדייק — הוא מונח על המדף של שרה.', en: 'Emigrated to Mandatory Palestine', tier: 'major', post: 'Left Vilnius with one suitcase, his tools, and the brass pocket-watch his father had carried. Photographed on the dock at Haifa the morning he landed — the suitcase and toolbox at his feet are everything he owned. The watch still keeps time today — it sits on Sarah’s shelf.' },
        { year: 1946, he: 'פתח חנות שעונים משלו', postHe: 'אחרי עשור של תיקונים ליד שולחנות של אחרים, חנות משלו ברחוב הרצל — זכוכית מגדלת על המצח, לוח שנה של יולי 1946 על הקיר, ומגש מלא מנגנונים פרוש על הבד השחור. השכנים אמרו שאפשר לכוון לפיו את הלב.', en: 'Opened his own watch shop', tier: 'major', post: 'After a decade of repairs at other men’s benches, a shop of his own on Herzl Street — loupe on his forehead, a July 1946 calendar on the wall, and a full tray of movements laid out on the black cloth. Neighbours said you could set your heart by him.' },
        { year: 1974, he: 'שעון הכיס, עדיין מדייק', postHe: 'במרפסת שלו על הכרמל, בן 71, הנמל שאליו הגיע ארבעים שנה קודם פרוש למטה. בידיו: שעון הכיס מפליז מווילנה. בכל יום שישי בדק אותו מול הרדיו; הוא לא טעה מעולם.', en: 'The pocket-watch, still keeping time', tier: 'minor', post: 'On his balcony on Mount Carmel, aged 71, the harbour he arrived at forty years earlier spread out below. In his hands: the brass pocket-watch from Vilnius. He checked it against the radio every Friday; it was never wrong.' } ],
      bio: { he: 'אבי המשפחה. שען שנשא את המקצוע — ושעון כיס קטן מפליז — מווילנה לחיפה.', en: 'Patriarch of the family. A watchmaker who carried the trade — and a small brass pocket-watch — from Vilnius to Haifa.' } },
    { id: 'miriam', gen: 0, sex: 'f', name: { en: 'Miriam Adler', he: 'מִרְיָם אַדְלֶר' },
      names: { birth: { en: 'Miriam Stern', he: 'מִרְיָם שְׁטֶרְן' } },
      nameChange: { year: 1929, kind: 'marriage', from: 'Stern', to: 'Adler',
        note: 'Became Miriam Adler on marrying Yosef in 1929; the bakery kept the Stern name over the door.' },
      birth: { year: 1908, place: 'Warsaw, Poland' }, death: { year: 1994, place: 'Haifa, Israel' },
      parents: [], milestones: [
        { year: 1909, he: 'תצלום ראשון', postHe: 'עוד לא בת שנה, בכובע תחרה על זרוע אמה בסטודיו בוורשה — מושיטה יד ישר אל המצלמה.', en: 'First photograph', tier: 'minor', post: 'Not yet one, in a lace bonnet on her mother’s arm at a Warsaw studio — reaching straight for the camera.' },
        { year: 1916, he: 'חלת יום שישי', postHe: 'בת שמונה, צמות הדוקות, נשלחת דרך החצר להביא את חלת יום שישי — צולמה באמצע השליחות, והחלה כבר חסרה ביס.', en: 'The Friday challah', tier: 'minor', post: 'Eight years old, braids done tight, sent across the courtyard for the Friday challah — photographed mid-errand, the loaf already one bite short.' },
        { year: 1924, he: 'בת שש עשרה, בוורשה', postHe: 'הצמה הגיעה עד המותניים. דיוקן סטודיו בגיל שש עשרה, שנים אחדות לפני שעזבה את ורשה לחיפה.', en: 'Sixteen, in Warsaw', tier: 'minor', post: 'The braid reached her waist. A studio portrait at sixteen, a few years before she left Warsaw for Haifa.' },
        { year: 1940, he: 'פתחה את מאפיית המשפחה', postHe: 'הבוקר הראשון: מפתחות ביד מתחת לשלט החדש „מאפיית שטרן” ברחוב הרצל. היא תנהל אותה ארבעים שנה.', en: 'Opened the family bakery', tier: 'major', post: 'The first morning: keys in hand under the brand-new STERN’S BAKERY sign on Herzl Street. She would run it for forty years.' },
        { year: 1950, he: 'מאחורי הדלפק', postHe: 'קמח עד המרפקים, צוחקת עם לקוחה קבועה מעבר לדלפק — מגשי חלות נערמים עד התקרה מאחוריה. הקופה מעולם לא ממש עבדה; את החשבונות עשתה בראש.', en: 'Behind the counter', tier: 'minor', post: 'Flour to the elbows, laughing with a regular across the counter — challah trays stacked to the ceiling behind her. The register never quite worked; she did the sums in her head.' },
        { year: 1988, he: 'עדיין ברחוב הרצל', postHe: 'החנות כבר עמדה ריקה, אבל רוב הבקרים עדיין הסתיימו מול הפתח הישן — משקפיים על שרוך, ידיים שלובות, מברכת את כולם בשמם.', en: 'Still on Herzl Street', tier: 'minor', post: 'The shop stood empty by then, but most mornings still ended outside the old doorway — glasses on a cord, arms folded, greeting everyone by name.' } ],
      bio: { he: 'אם המשפחה, לבית שטרן. ניהלה את המאפייה ברחוב הרצל ארבעים שנה; כל השכונה הכירה את החלות שלה.', en: 'Matriarch, born Miriam Stern. Ran the bakery on Herzl Street for forty years; everyone in the neighbourhood knew her challah.' } },

    // ---- Gen 1 — children of Yosef & Miriam ----
    { id: 'david',  gen: 1, sex: 'm', name: { en: 'David Adler',   he: 'דָּוִד אַדְלֶר' },
      birth: { year: 1931, place: 'Haifa, Israel' }, death: { year: 2010, place: 'Tel Aviv, Israel' },
      parents: ['yosef', 'miriam'], milestones: [
        { year: 1933, he: 'צעדים ראשונים', postHe: 'בן שנתיים בחצר, צוחק בדרכו אחרי הליכון עץ. מרים נשבעה שמעולם לא זחל — עבר ישר לריצה.', en: 'First steps', tier: 'minor', post: 'Two years old in the courtyard, laughing his way along behind a wooden walker. Miriam swore he never once crawled — he went straight to running.' },
        { year: 1939, he: 'למד לקלוע חלה', postHe: 'בן שמונה, שרוולים מופשלים, לשון בחוץ מרוב ריכוז ליד שולחן העבודה של המאפייה השכונתית שבה אפתה מרים לפני שפתחה משלה. הקליעות הראשונות שלו יצאו עקומות, והלקוחות קנו אותן בכל זאת.', en: 'Learned to braid challah', tier: 'minor', post: 'Eight years old, sleeves rolled, tongue out in concentration at the workbench of the neighbourhood bakery where Miriam baked before opening her own. His first braids came out crooked, and the customers bought them anyway.' },
        { year: 1946, he: 'חילק לחם בכל חיפה', postHe: 'בן חמש עשרה, עם אופני המשלוחים וסל הנצרים, מוריד את כיכרות הבוקר לנמל לפני בית הספר. הכיר כל רחוב מדרגות בחיפה וטען שהאופניים מכירים אותם טוב ממנו.', en: 'Delivered bread across Haifa', tier: 'minor', post: 'Fifteen, with the delivery bicycle and its wicker basket, running the morning loaves down to the port before school. He knew every stair-street in Haifa and claimed the bicycle knew them better.' },
        { year: 1949, he: 'שירת בצבא', postHe: 'שירות סדיר עם שני חברים מהשכונה וג׳יפ מבוגר מכולם. כתב הביתה כל שבוע — בעיקר לשאול מה בתנורים.', en: 'Served in the army', tier: 'minor', post: 'National service with two friends from the neighbourhood and a jeep older than any of them. He wrote home every week — mostly to ask what was in the ovens.' },
        { year: 1957, he: 'קיבל את מאפיית המשפחה', postHe: 'כשידיה של מרים כבר התקשו ללוש, חזר דוד מהעיר ולקח את התנורים. הוא שמר על המחמצת שלה בחיים — אותה מחמצת, מוזנת מדי יום, שחנה אופה איתה עד היום.', en: 'Took over the family bakery', tier: 'major', post: 'When Miriam’s hands grew too stiff to knead, David came home from the city and took the ovens. He kept her sourdough starter alive — the same one, fed daily, that Hannah bakes with now.' },
        { year: 1966, he: 'שנים ליד התנורים', postHe: 'האמצע הארוך של חיי העבודה שלו: קם בשלוש, המרדה שחוקה במקום שבו אחזו ידיו, המדפים הקדמיים מלאים לפני שהעיר התעוררה. אמר שהתנור מדייק יותר מהשעונים של אביו.', en: 'Years at the ovens', tier: 'minor', post: 'The long middle of his working life: up at three, the peel worn smooth where his hands went, the front racks filled before the city woke. He said the oven kept better time than his father’s watches.' },
        { year: 1969, he: 'שנות השקט שאחרי רבקה', postHe: 'תקופה קשה. גידל את אהרן ולאה לבד, המאפייה והילדים, עד רחל.', en: 'Years of quiet after Rivka', tier: 'minor', post: 'A hard stretch. He raised Aaron and Leah alone, the bakery and the children, until Rachel.' },
        { year: 2004, he: 'ראש שולחן יום שישי', postHe: 'בשנות תל אביב, ארוחת יום שישי הייתה שלו: כל המשפחה צפופה סביב שולחן אחד, ודוד נואם בראשו. אסור היה לפנות צלחות עד שהסיפור האחרון נגמר.', en: 'Head of the Friday table', tier: 'minor', post: 'In the Tel Aviv years, Friday dinner was his: the whole family crowded round one table, David holding forth at the head of it. Nobody was allowed to clear the plates until the last story was finished.' } ],
      bio: { he: 'דור הגשר. נשוי פעמיים — תחילה לרבקה, אחר כך לרחל — ואב למשפחה שגדלה בשני פרקים.', en: 'The bridge generation. Twice married — first to Rivka, then to Rachel — and father to a family that grew in two chapters.' } },
    { id: 'sarah',  gen: 1, sex: 'f', name: { en: 'Sarah Adler',   he: 'שָׂרָה אַדְלֶר' },
      birth: { year: 1934, place: 'Haifa, Israel' }, death: null,
      parents: ['yosef', 'miriam'], milestones: [
        { year: 1942, he: 'לימדה את הבובות אותיות', postHe: 'הרבה לפני שהייתה לה כיתה, סידרה שרה את הבובות על רצפת הדירה ולימדה אותן מתוך ספר לימוד פתוח, לוח גיר שעון על כיסא. במשפחה מתבדחים שהייתה מורה בגיל שמונה ולא הפסיקה מאז.', en: 'Taught her dolls their letters', tier: 'minor', post: 'Long before she had a classroom, Sarah lined her dolls up on the apartment floor and taught them from an open schoolbook, a chalk slate propped against a chair. The family jokes she was a teacher at eight and never stopped.' },
        { year: 1951, he: 'סיימה בית ספר בחיפה', postHe: 'ראשונה בכיתתה, ולא נראתה מעולם בלי ערימת ספרים. ישבה לדיוקן על גדר האבן הנמוכה מול הבית — הביטה למצלמה ישר בעיניים — ובאותו סתיו יצאה לסמינר למורות.', en: 'Finished school in Haifa', tier: 'minor', post: 'Top of her class and never seen without a stack of books. She sat for a portrait on the low stone wall outside the house — looked the camera dead level in the eye — and left for teachers’ college that autumn.' },
        { year: 1956, he: 'נעשתה מורה', postHe: 'לימדה כיתה א׳ בבית הספר ביאליק ארבעים ושלוש שנים. חצי חיפה למדה ממנה את האותיות.', en: 'Became a schoolteacher', tier: 'major', post: 'Taught first grade at the Bialik school for forty-three years. Half of Haifa learned their letters from her.' },
        { year: 1970, he: 'שנים מול הלוח', postHe: 'הלב הארוך של הקריירה: גיר ביד, משקפי חתול, קרדיגן מסודר, וכיתה מלאה בני שש מתמודדים עם האותיות הראשונות שלהם. הייתה משתיקה כיתה במבט אחד.', en: 'Years at the blackboard', tier: 'minor', post: 'The long heart of her career: chalk in hand, cat-eye glasses, a neat cardigan, and a room full of six-year-olds working through their first Hebrew letters. She could settle a class with a single look.' },
        { year: 1999, he: 'פרשה אחרי 43 שנות הוראה', postHe: 'מילאו את אולם בית הספר בקישוטי נייר והגישו לה זר עצום. קריירה שלמה של עמיתים עמדה ומחאה כפיים, והיא נתפסה איפשהו בין צחוק לבכי.', en: 'Retired after 43 years teaching', tier: 'minor', post: 'They filled the school hall with paper decorations and handed her an enormous bouquet. A career’s worth of colleagues stood and applauded, and she was caught somewhere between laughing and crying.' },
        { year: 2005, he: 'נעשתה שומרת הסיפורים', postHe: 'אחרי שמרים ודוד הלכו, שרה נעשתה זו שזוכרת — השמות, התאריכים, מי התחתן עם מי ולמה. כל הרישום הזה התחיל ליד שולחן המטבח שלה.', en: 'Became the family’s storykeeper', tier: 'major', post: 'After Miriam and David were gone, Sarah became the one who remembered — the names, the dates, who married whom and why. This whole record began at her kitchen table.' },
        { year: 2026, he: 'עדיין שומרת את הסיפורים', postHe: 'בת תשעים ושתיים, עדיין חדה ועדיין זו שזוכרת. שולחן המטבח שלה קבור תחת אלבומים פתוחים וטבלאות בכתב יד; שאלו אותה מי זה מישהו — היא תצמיד אצבע לתצלום ותספר את הסיפור כולו.', en: 'Still keeping the family’s stories', tier: 'minor', post: 'At ninety-two, still sharp and still the one who remembers. Her kitchen table stays buried under open albums and handwritten charts; ask her who anyone is and she’ll pin the photograph down with one finger and tell you the whole story.' } ],
      bio: { he: 'מעולם לא נישאה; שומרת סיפורי המשפחה. דודה-רבתא לדור שעזרה לגדל. חדה גם בתשעים.', en: 'Never married, the keeper of the family stories. Great-aunt to a generation she helped raise. Still sharp at ninety.' } },

    // David's first wife (married in) — died young
    { id: 'rivka',  gen: 1, sex: 'f', name: { en: 'Rivka Adler', he: 'רִבְקָה אַדְלֶר' },
      names: { birth: { en: 'Rivka Katz', he: 'רִבְקָה כַּץ' } },
      nameChange: { year: 1958, kind: 'marriage', from: 'Katz', to: 'Adler',
        note: 'Took the Adler name on marrying David in 1958.' },
      birth: { year: 1936, place: 'Jerusalem, Israel' }, death: { year: 1968, place: 'Haifa, Israel' },
      parents: [], milestones: [
        { year: 1938, he: 'תצלום ראשון', postHe: 'בת שנתיים בכובע סרוג, מורמת אל החלון המקושת של דירת המשפחה בירושלים להביט ברחוב שלמטה.', en: 'First photograph', tier: 'minor', post: 'Two years old in a crocheted bonnet, held up to the arched window of the family flat in Jerusalem to watch the street below.' },
        { year: 1944, he: 'החתלתול על המדרגות', postHe: 'בת שמונה על מדרגות האבן של סמטה בעיר העתיקה, חתלתול רחוב בחיקה. הוא הלך אחריה הביתה; אמה העמידה פנים שלא שמה לב, שבוע שלם.', en: 'The kitten on the steps', tier: 'minor', post: 'Eight years old on the stone steps of an Old City lane, a stray kitten in her lap. It followed her home; her mother pretended not to notice for a week.' },
        { year: 1953, he: 'בת שבע עשרה, בירושלים', postHe: 'על רקע קיר אבן חמים משמש, בשמלה הפרחונית — הקיץ שלפני שעברה לחיפה, שם תפגוש את דוד.', en: 'Seventeen, in Jerusalem', tier: 'minor', post: 'Against a sun-warmed stone wall in her floral dress — the summer before she moved to Haifa, where she would meet David.' },
        { year: 1966, he: 'במרפסת בחיפה', postHe: 'כביסה על החבל והים מעבר לה: רבקה עם לאה הקטנה על המותן במרפסת החיפאית. אחד התצלומים האחרונים שלה.', en: 'On the balcony in Haifa', tier: 'minor', post: 'Laundry on the line and the sea beyond: Rivka with little Leah on her hip on the Haifa balcony. One of the last photographs of her.' } ],
      bio: { he: 'אשתו הראשונה של דוד, לבית כץ. אמם של אהרן ולאה. נפטרה צעירה, ב-1968.', en: "David's first wife, born Rivka Katz. Mother of Aaron and Leah. Died young, in 1968." } },
    // David's second wife (married in)
    { id: 'rachel', gen: 1, sex: 'f', name: { en: 'Rachel Adler', he: 'רָחֵל אַדְלֶר' },
      names: { birth: { en: 'Rachel Cohen', he: 'רָחֵל כֹּהֵן' } },
      nameChange: { year: 1971, kind: 'marriage', from: 'Cohen', to: 'Adler',
        note: 'Took the Adler name on marrying David in 1971.' },
      birth: { year: 1941, place: 'Tel Aviv, Israel' }, death: null,
      parents: [], milestones: [
        { year: 1943, he: 'תצלום ראשון', postHe: 'בת שנתיים במרפסת בתל אביב, צוחקת אל כל הרחוב שלמטה. העיר הלבנה הקטנה מאחוריה הייתה בקושי מבוגרת ממנה.', en: 'First photograph', tier: 'minor', post: 'Two years old on the balcony in Tel Aviv, laughing at the whole street below. The little white city behind her was barely older than she was.' },
        { year: 1949, he: 'האקליפטוס', postHe: 'אלופת ההפסקות של החצר: בת שמונה והכי גבוה על האקליפטוס, רגליים יחפות מתנדנדות בזמן שהכיתה צופה מלמטה.', en: 'The eucalyptus tree', tier: 'minor', post: 'Recess champion of the schoolyard: eight years old and highest up the eucalyptus, bare feet swinging while the class watched from below.' },
        { year: 1958, he: 'בת שבע עשרה, על הטיילת', postHe: 'צוחקת עם חברות מעל חוף תל אביב, סירות דיג מעבר לשובר הגלים. אמרה לימים שזה היה הקיץ שבו הרגישה הכי היא-עצמה.', en: 'Seventeen, on the promenade', tier: 'minor', post: 'Laughing with girlfriends above the Tel Aviv beach, fishing boats out past the breakwater. She said later this was the summer she felt most herself.' },
        { year: 1979, he: 'שלושים ושמונה נרות', postHe: 'יום הולדתה במטבח החיפאי: עוגת שוקולד על הצלחת החגיגית, וידיים קטנות מגיעות משני הצדדים עוד לפני שנגמר השיר.', en: 'Thirty-eight candles', tier: 'minor', post: 'Her birthday in the Haifa kitchen: chocolate cake on the good plate, and small hands arriving from both sides before the song was finished.' },
        { year: 2026, he: 'תה ליד החלון', postHe: 'בת שמונים וחמש, בכורסה ליד החלון — תה חזק בכלי החרסינה הטובים, השמיכה הסרוגה, ולוח שנה של 2026 שכבר מתמלא בימי הולדת של נכדים.', en: 'Tea by the window', tier: 'minor', post: 'Eighty-five, in the armchair by the window — strong tea in the good china, the crocheted blanket, and a 2026 calendar already filling up with grandchildren’s birthdays.' } ],
      bio: { he: 'אשתו השנייה של דוד, לבית כהן; אם חורגת לאהרן וללאה ואמו של דניאל.', en: "David's second wife, born Rachel Cohen; step-mother to Aaron and Leah and mother of Daniel." } },

    // Side-link outsider — the neighbour who raised David
    { id: 'moshe',  gen: 1, sex: 'm', name: { en: 'Moshe Gold',    he: 'מֹשֶׁה גּוֹלְד' },
      birth: { year: 1926, place: 'Haifa, Israel' }, death: { year: 2009, place: 'Haifa, Israel' },
      parents: [], milestones: [
        { year: 1928, he: 'תצלום הגיגית', postHe: 'בן שנתיים ומאושר, בגיגית העץ שהצלם החזיק בדיוק בשביל זה. השיער לא נרגע מעולם.', en: 'The washtub photograph', tier: 'minor', post: 'Two years old and delighted, in the wooden washtub the photographer kept for exactly this. The hair never calmed down.' },
        { year: 1934, he: 'דיג על שובר הגלים', postHe: 'בן שמונה עם מקל, חוט וסבלנות אינסופית על שובר הגלים של נמל חיפה. טען שפעם תפס משהו; איש לא ראה את זה מעולם.', en: 'Fishing off the breakwater', tier: 'minor', post: 'Eight years old with a stick, a string and infinite patience on the Haifa port breakwater. He claimed he once caught something; nobody ever saw it.' },
        { year: 1943, he: 'עובד בנמל', postHe: 'בן שבע עשרה וכבר סוור בנמל חיפה — לחם ביד בהפסקת הצהריים, ולוח השש-בש אף פעם לא רחוק.', en: 'Working the port', tier: 'minor', post: 'Seventeen and already a dockhand at Haifa port — bread in hand at the midday break, the backgammon board never far.' },
        { year: 1968, he: 'מתקן האופניים', postHe: 'המתקן-של-הכול של השכונה, מתקן אופני ילד על מדרגות הכניסה. אחרי שרבקה נפטרה באותה שנה, האופניים של ילדי אדלר לא נשארו מקולקלים הרבה זמן.', en: 'The bicycle mender', tier: 'minor', post: 'The neighbourhood’s fixer of everything, mending a child’s bicycle on the front steps. After Rivka died that year, the Adler children’s bikes never stayed broken for long.' },
        { year: 2005, he: 'שש-בש בקיוסק', postHe: 'בן שבעים ותשע, בקיוסק הפינתי שלו — תה בכוס זכוכית, לוח פתוח, מקבל כל מתמודד. בדרך כלל ניצח.', en: 'Backgammon at the kiosk', tier: 'minor', post: 'Seventy-nine, at his corner kiosk — tea in a glass, board open, taking on all comers. He usually won.' } ],
      bio: { he: 'שכן, לא קרוב משפחה. השגיח על דוד בילדותו כשהמאפייה עיכבה את הוריו עד מאוחר.', en: 'A neighbour, not a relative. Looked after David as a boy when the bakery kept his parents late.' } },

    // ---- Gen 2 ----
    { id: 'aaron',  gen: 2, sex: 'm', name: { en: 'Aaron Adler',   he: 'אַהֲרֹן אַדְלֶר' },
      birth: { year: 1960, place: 'Haifa, Israel' }, death: null,
      parents: ['david', 'rivka'], milestones: [
        { year: 1962, he: 'תצלום ראשון', postHe: 'בן שנתיים בפתח מאפיית המשפחה, מורם על זרוע אביו — מתעניין הרבה יותר במאוורר התקרה מאשר במצלמה.', en: 'First photograph', tier: 'minor', post: 'Two years old at the door of the family bakery, hoisted on his father’s arm — far more interested in the ceiling fan than in the camera.' },
        { year: 1968, he: 'שעון שולחן המטבח', postHe: 'בן שמונה, הדם של סבא יוסף ניכר: השעון המעורר מפורק על שולחן הסלון — ולתדהמת כולם, מורכב חזרה ומתקתק עד ארוחת הערב.', en: 'The kitchen-table clock', tier: 'minor', post: 'Eight years old, grandfather Yosef’s blood showing: the alarm clock disassembled across the living-room table — and, to everyone’s surprise, back together and ticking by supper.' },
        { year: 1976, he: 'מלחים מתחת לפנטומים', postHe: 'בן שש עשרה, פנטומים מודבקים מעל השולחן, בונה ערכות רדיו מחלקי עודפים. סימני הצריבה של המלחם נשארו על השולחן עד שהדירה נמכרה.', en: 'Soldering under the Phantoms', tier: 'minor', post: 'Sixteen, F-4 Phantoms taped over the desk, building radio kits from surplus parts. The soldering-iron scorch marks stayed on that desk until the flat was sold.' },
        { year: 1985, he: 'עבר לתל אביב', postHe: 'בן עשרים וחמש, דירה ראשונה משלו: גג תל אביבי בשקיעה, ארגזי המעבר עוד מסומנים „מגורים — אהרן”, בירה מורמת עוד לפני שנפתחה אחת.', en: 'Moved to Tel Aviv', tier: 'major', post: 'Twenty-five, first flat of his own: a Tel Aviv rooftop at sunset, the moving boxes still labelled מגורים — אהרן, a beer raised before a single one was opened.' },
        { year: 1995, he: 'ליד שולחן השרטוט', postHe: 'שנות העבודה: שרטוטים, קלסרים ומחשב בז׳, כרזת תערוכת ההנדסה 1994 מעל השולחן. את הטיוטה הראשונה של כל תוכנית עדיין שרטט ביד.', en: 'At the drawing board', tier: 'minor', post: 'The working years: blueprints, binders and a beige PC, the 1994 Engineering Expo poster over the desk. He still drew the first pass of every plan by hand.' },
        { year: 2001, he: 'ייסד משרד הנדסה קטן', postHe: 'מבריג את שמו לדלת של חדר 20 — „אהרן אדלר ושות׳, מהנדס אזרחי” — בזמן שאלי ומעין צוחקים כמה זמן לקח לו ליישר את השלט.', en: 'Founded a small engineering firm', tier: 'major', post: 'Screwing his own name to the door of room 20 — Aaron Adler & Associates, Civil Engineer — while Eli and Maya laughed at how long he took to get it level.' },
        { year: 2026, he: 'קפה במרפסת', postHe: 'בן שישים ושש: קפה במרפסת בין עץ הזית לבוגנוויליה, והעיר שעזר להנדס צומחת לגובה מאחוריו.', en: 'Coffee on the mirpeset', tier: 'minor', post: 'Sixty-six: coffee on the balcony between the olive tree and the bougainvillea, the city he helped engineer growing taller behind him.' } ],
      bio: { he: 'בכורם של דוד ורבקה. מהנדס בתל אביב.', en: 'Eldest of David & Rivka. An engineer in Tel Aviv.' } },
    { id: 'leah',   gen: 2, sex: 'f', name: { en: 'Leah Friedman',  he: 'לֵאָה פְרִידְמַן' },
      names: { birth: { en: 'Leah Adler', he: 'לֵאָה אַדְלֶר' } },
      nameChange: { year: 1989, kind: 'marriage', from: 'Adler', to: 'Friedman',
        note: 'Took the Friedman name when she married Michael in 1989.' },
      birth: { year: 1963, place: 'Haifa, Israel' }, death: null,
      parents: ['david', 'rivka'], milestones: [
        { year: 1965, he: 'תצלום ראשון', postHe: 'בת שנתיים, מוסתרת בסל הכביסה במרפסת החיפאית ומרוצה מעצמה מאוד. איש לא זוכר מי שם אותה שם; כולם לוקחים קרדיט.', en: 'First photograph', tier: 'minor', post: 'Two years old, stowed away in the laundry basket on the Haifa balcony and delighted with herself. Nobody remembers who put her there; everybody claims credit.' },
        { year: 1971, he: 'קונצרט במטבח', postHe: 'בת שמונה, כף עץ במקום מיקרופון, נותנת למטבח הופעה שלמה — כולל ברכיים שרוטות. הקהל שלה לא פספס הופעה.', en: 'Concert in the kitchen', tier: 'minor', post: 'Eight years old, wooden spoon for a microphone, giving the kitchen a full concert — scabbed knees and all. Her audience never missed a show.' },
        { year: 1979, he: 'הגיטרה על שובר הגלים', postHe: 'בת שש עשרה, ישיבה מזרחית על שובר הגלים בבת גלים עם הגיטרה, הנרתיק פתוח לידה יותר מתוך תקווה מאשר מתוך צורך.', en: 'The guitar on the seawall', tier: 'minor', post: 'Sixteen, cross-legged on the Bat Galim seawall with her guitar, the case open beside her more from hope than need.' },
        { year: 1989, he: 'נישאה למיכאל; קיבלה את השם פרידמן', postHe: 'מתחת לשרשרת האורות בחצר: לאה ומיכאל, רגע אחרי החתונה. את הפרחים מהשיער שמרה מיובשים בתוך ספר.', en: 'Married Michael; took the name Friedman', tier: 'major', post: 'Under the string lights in the courtyard: Leah and Michael, just married. She kept the flowers from her hair pressed in a book.' },
        { year: 1998, he: 'הגינה בקריות', postHe: 'שתילות אביב בגינה האחורית — מגש שתילים, חנה מפקחת, ובנימין הקטן בוחן את האדמה. העגבניות לא צמחו אף פעם.', en: 'The garden in the Krayot', tier: 'minor', post: 'Spring planting in the back garden — a tray of seedlings, Hannah supervising, and little Benjamin inspecting the dirt. The tomatoes never once came up.' },
        { year: 2026, he: 'נרות שבת', postHe: 'בת שישים ושלוש, מדליקה נרות בשולחן שלה, הדור הבא מצטופף סביב ומחכה לחלה.', en: 'Shabbat candles', tier: 'minor', post: 'Sixty-three, lighting the candles at her own table, the next generation crowded round waiting for the challah.' } ],
      bio: { he: 'בתם של דוד ורבקה. קיבלה את השם פרידמן כשנישאה למיכאל.', en: 'Daughter of David & Rivka. Took the Friedman name when she married Michael.' } },
    { id: 'daniel', gen: 2, sex: 'm', name: { en: 'Daniel Adler',  he: 'דָּנִיֵּאל אַדְלֶר' },
      birth: { year: 1973, place: 'Haifa, Israel' }, death: null,
      parents: ['david', 'rachel'], milestones: [
        { year: 1975, he: 'תצלום ראשון', postHe: 'בן שנתיים, שקוע בשינה על חזה אביו על הספה הפרחונית — דוד נרדם גם הוא בתוך דקה. רחל צילמה; התמונה נשארה ממוסגרת ליד מיטתה מאז ומעולם.', en: 'First photograph', tier: 'minor', post: 'Two years old, out cold on his father’s chest on the flowered sofa — David asleep too within the minute. Rachel took the picture; it stayed framed by her bed ever after.' },
        { year: 1981, he: 'האינסטמטיק', postHe: 'בן שמונה, ומצלמת האינסטמטיק המשפחתית סוף סוף בידיו. שרף את כל קוביית הפלש על החתול עד הצהריים — הצלם כבר היה בלתי ניתן לטעות.', en: 'The Instamatic', tier: 'minor', post: 'Eight years old and the family Instamatic finally in his hands. He burned the whole flash cube on the cat by lunchtime — the photographer was already unmistakable.' },
        { year: 1989, he: 'על הגג עם הקנון', postHe: 'בן שש עשרה, על הגג החיפאי בין הערביים עם קנון יד שנייה וחולצת סמית׳ס, לומד את האור שבין האנטנות לים.', en: 'On the roof with the Canon', tier: 'minor', post: 'Sixteen, up on the Haifa roof at dusk with a secondhand Canon and a Smiths t-shirt, learning the light between the antennas and the sea.' },
        { year: 2004, he: 'הכיר את נועה', postHe: 'ליד דוכן הפלאפל, צוחק עם נועה מול המסך של המצלמה הכסופה הקטנה — התמונה הראשונה של שניהם, שצילם דניאל במרחק זרוע.', en: 'Partnered with Noa', tier: 'major', post: 'At the falafel counter, laughing with Noa over the little silver camera’s screen — the first photo of the two of them, taken by Daniel at arm’s length.' },
        { year: 2026, he: 'הסטודיו', postHe: 'בן חמישים ושלוש, בפתח הסטודיו שלו — גיליונות קונטקט על לוח השעם, מצלמה על הכתף. הארכיונאי הלא-רשמי של המשפחה: רוב התצלומים ברישום הזה עברו דרך ידיו.', en: 'The studio', tier: 'minor', post: 'Fifty-three, in the doorway of his studio — contact sheets on the corkboard, camera on the shoulder. The family’s unofficial archivist: most of the photographs in this record passed through his hands.' } ],
      bio: { he: 'בנם של דוד ורחל — אח למחצה של אהרן ולאה. צלם.', en: 'Son of David & Rachel — half-brother to Aaron and Leah. A photographer.' } },

    // Gen 2 spouses (married in)
    { id: 'tamar',  gen: 2, sex: 'f', name: { en: 'Tamar Levi',    he: 'תָּמָר לֵוִי' },
      birth: { year: 1962, place: 'Beersheba, Israel' }, death: null, parents: [], milestones: [
        { year: 1964, he: 'תצלום ראשון', postHe: 'בת שנתיים בצל החצר בבאר שבע, כובע עד הגבות, כבר בוחנת את המצלמה בחשדנות מסוימת.', en: 'First photograph', tier: 'minor', post: 'Two years old in the shade of the courtyard in Beersheba, hat down to her eyebrows, already regarding the camera with some suspicion.' },
        { year: 1970, he: 'תה לשישה', postHe: 'בת שמונה, מוזגת תה לקהל סבלני מאוד של שישה. כולם שתו לפי הסדר ואיש לא הורשה לקום מוקדם.', en: 'Tea for six', tier: 'minor', post: 'Eight years old, pouring tea for a very patient audience of six. Everyone drank in order and nobody was allowed to leave early.' },
        { year: 1975, he: 'ספרי לימוד', postHe: 'בת שלוש עשרה, הספרים מוחזקים כמו מגן בדרך הביתה — הרצינית של הכיתה, אם כי החברה הכי טובה שלה לא הפסיקה לצחוק.', en: 'Schoolbooks', tier: 'minor', post: 'Thirteen, books held like a shield on the walk home — the serious one of her class, though her best friend never stopped laughing.' },
        { year: 1978, he: 'החולצה הרקומה', postHe: 'בת שש עשרה, בחולצה שרקמה סבתה, מסוככת על עיניה בפתח הבית הישן של המשפחה.', en: 'The embroidered blouse', tier: 'minor', post: 'Sixteen, in the blouse her grandmother embroidered, shading her eyes in the doorway of the old family house.' },
        { year: 1989, he: 'הפנקסים', postHe: 'בת עשרים ושבע וכבר מיישרת את החשבונות של חצי שכונה — הקסיו, הקבלות, וארון התיקים שמעולם לא נסגר עד הסוף.', en: 'The ledgers', tier: 'minor', post: 'Twenty-seven and already keeping half the neighbourhood’s books straight — the Casio, the receipts, the filing cabinet that never quite closed.' },
        { year: 1997, he: 'משרד משלה', postHe: 'שנות תל אביב: חשבונות של לקוחות מעל קפה שחור בבית הקפה הפינתי, משקפי הקריאה בהישג יד. אהבה את הרעש בזמן העבודה.', en: 'Her own practice', tier: 'minor', post: 'The Tel Aviv years: clients’ accounts over black coffee at the corner café, reading glasses within reach. She liked the noise while she worked.' },
        { year: 2026, he: 'הספסל בשדרה', postHe: 'בת שישים וארבע, על ספסל השדרה בשעת הזהב, שומרת על קורקינט של נכד שרץ קדימה בינתיים.', en: 'The bench on the boulevard', tier: 'minor', post: 'Sixty-four, on the boulevard bench at golden hour, minding a grandchild’s scooter while its owner runs ahead.' } ],
      bio: { he: 'אשתו של אהרן.', en: "Aaron's wife." } },
    { id: 'michael',gen: 2, sex: 'm', name: { en: 'Michael Friedman', he: 'מִיכָאֵל פְרִידְמַן' },
      birth: { year: 1959, place: 'London, England' }, death: null, parents: [], milestones: [
        { year: 1961, he: 'תצלום ראשון', postHe: 'בן שנתיים בעגלה על המדשאה הציבורית, כפפות על חוטים, לא מתרשם מהאביב האנגלי.', en: 'First photograph', tier: 'minor', post: 'Two years old in the pram on the common, mittens on strings, unimpressed by the English spring.' },
        { year: 1967, he: 'אוסף הקלפים', postHe: 'בן שמונה, בקומה העליונה של קו 137 עם קלפי הכדורגל. את הקלף שהוא מרים היה ההחלפה הטובה — עד היום יגיד לך איזה קלף זה היה.', en: 'The card collection', tier: 'minor', post: 'Eight, on the top deck of the 137 with the football cards. The one he’s holding up was the good swap — he could tell you which one it was to this day.' },
        { year: 1971, he: 'עדיין אוסף', postHe: 'בן שתים עשרה, אותו קו, אותם קלפים — ערימה עבה יותר ומיקוחים קשים יותר. הכרטיסנים הכירו אותו בשמו.', en: 'Still collecting', tier: 'minor', post: 'Twelve, same route, same cards — a thicker stack and harder bargains. The conductors knew him by name.' },
        { year: 1975, he: 'בן שש עשרה, אחרי הכדורגל', postHe: 'בן שש עשרה בדרך הביתה, רטוב עד לשד עצמותיו ומרוצה מזה. המגבת הגיעה משכן; הסיפור למה — השתנה בכל פעם שסיפר אותו.', en: 'Sixteen, after football', tier: 'minor', post: 'Sixteen on the walk home, soaked through and grinning about it. The towel came from a neighbour; the story of why changed every time he told it.' },
        { year: 1985, he: 'ארץ חדשה, עבודה ראשונה', postHe: 'שנה אחרי הנחיתה בישראל: לילות מאוחרים ליד מכונת הצילום בעבודה הראשונה, תה ביד, לומד עברית מהר יותר משיטת התיוק.', en: 'A new country, a first job', tier: 'major', post: 'A year after landing in Israel: late nights by the photocopier at his first job, tea in hand, learning Hebrew faster than the filing system.' },
        { year: 1994, he: 'על המנגל', postHe: 'יום העצמאות בחצר, מגבת על הכתף — מזמן אזרח לכל דבר: לאיש אחר אסור היה להתקרב לשיפודים.', en: 'On the grill', tier: 'minor', post: 'Independence Day in the yard, towel on the shoulder — fully naturalised by now: nobody else was allowed near the skewers.' },
        { year: 2026, he: 'תשבץ סוף השבוע', postHe: 'בן שישים ושבע, בכורסה שלו עם תשבץ סוף השבוע, עט ולא עיפרון — ההרגל האנגלי האחד שלא ויתר עליו מעולם.', en: 'The weekend crossword', tier: 'minor', post: 'Sixty-seven, in his chair with the weekend crossword, pen not pencil — the one English habit he never gave up.' } ],
      bio: { he: 'בעלה של לאה; נולד בלונדון ועלה לישראל ב-1984.', en: "Leah's husband; born in London, moved to Israel in 1984." } },
    { id: 'noa',    gen: 2, sex: 'f', name: { en: 'Noa Bar',       he: 'נוֹעָה בַּר' },
      birth: { year: 1976, place: 'Tel Aviv, Israel' }, death: null, parents: [], milestones: [
        { year: 1978, he: 'תצלום ראשון', postHe: 'בת שנתיים וזועמת מרוב אושר בלול, באמצע צעקה — יד אמה עם הטבעות נראית בקצה הפריים, מוכנה לתפוס אותה.', en: 'First photograph', tier: 'minor', post: 'Two years old and furious with delight in the playpen, mid-shout — her mother’s ringed hand just visible at the edge, ready to catch her.' },
        { year: 1984, he: 'הגג', postHe: 'על גג בפלורנטין בשעת הזהב, בין דודי השמש לחבלי הכביסה — הנוף שבתוכו גדלה.', en: 'The rooftop', tier: 'minor', post: 'Up on the Florentin rooftop at golden hour among the solar heaters and the washing lines — the view she grew up inside of.' },
        { year: 1989, he: 'קיצים על הגג', postHe: 'בת שלוש עשרה, טי-שירט ענקית קשורה במותן, אותם גגות של דרום תל אביב נערמים מאחוריה. בקיץ היא כמעט גרה שם למעלה.', en: 'Rooftop summers', tier: 'minor', post: 'Thirteen, an oversized t-shirt knotted at the hip, the same south Tel Aviv rooftops stacked behind her. She practically lived up there in summer.' },
        { year: 1992, he: 'NOA, TLV ׳92', postHe: 'בת שש עשרה, דובון צבאי עודפים ומגפי דוקטורס מוכים מול קיר מרוסס בדרום העיר — שמה כבר מרוסס על הבטון מאחוריה, ליד של מישהו אחר.', en: 'NOA, TLV ’92', tier: 'major', post: 'Sixteen, a surplus M-65 and battered Docs against a tagged wall in the south of the city — her name already sprayed on the concrete behind her, next to someone else’s.' },
        { year: 2002, he: 'מעבדת הפיתוח בפינה', postHe: 'מאחורי הדלפק של חנות פיתוח התמונות השכונתית, קודאק גולד ופוג׳י סופריה נערמים על הזכוכית. לשם המשיך להגיע צלם מסוים עם גלילים לפיתוח, הרבה לפני שאזר אומץ להגיד משהו.', en: 'The film lab on the corner', tier: 'major', post: 'Behind the counter of the neighbourhood photo-development shop, Kodak Gold and Fuji Superia stacked on the glass. It’s where a certain photographer kept turning up with rolls to develop, long before he worked up the nerve to say much.' },
        { year: 2026, he: 'קפה בין הצמחים', postHe: 'בת חמישים, במטבח עמוס הצמחים עם ספל הקרמיקה הכחול, גגות תל אביב שעליהם גדלה עדיין מעבר לחלון.', en: 'Coffee among the plants', tier: 'minor', post: 'Fifty, in the plant-crowded kitchen with the blue ceramic mug, the Tel Aviv rooftops she was raised on still out the window.' } ],
      bio: { he: 'בת זוגו של דניאל. הם מעולם לא נישאו.', en: "Daniel's partner. They never married." } },

    // Side-link outsider — godparent
    { id: 'dov',    gen: 2, sex: 'm', name: { en: 'Dov Weiss',     he: 'דּוֹב וַיְס' },
      birth: { year: 1955, place: 'Haifa, Israel' }, death: null, parents: [], milestones: [
        { year: 1957, he: 'תצלום ראשון', postHe: 'נשקל על משקל המטבח בדירה החיפאית, ידיים מונפות באוויר ומאושר מזה — הטקס השבועי של אמו, הפעם מונצח לאלבום.', en: 'First photograph', tier: 'minor', post: 'Weighed on the kitchen scale in the Haifa flat, arms flung up and delighted about it — his mother’s weekly ritual, this time recorded for the album.' },
        { year: 1963, he: 'המגרש השכונתי', postHe: 'בן שמונה, אוחז בכדור הטוב על מגרש העפר בין השיכונים בחיפה. כבר אז זה שבוחר את הקבוצות — ואיכשהו תמיד זה ששומר על הכדור.', en: 'The neighbourhood pitch', tier: 'minor', post: 'Eight, clutching the good ball on the dust lot between the Haifa housing blocks. Already the one who picked the teams — and somehow always the one who kept the ball.' },
        { year: 1968, he: 'סבל אצל הירקן', postHe: 'בן שלוש עשרה, גורר ארגז במעלה מדרגות השוק תמורת כמה אגורות, אחיו הקטן משתרך מאחור. המשכורת הראשונה שלו, שבוזבזה באותו אחר צהריים.', en: 'Carrying for the greengrocer', tier: 'minor', post: 'Thirteen, hauling a crate up the market steps for a few agorot, his little brother trailing behind. His first wages, spent the same afternoon.' },
        { year: 1973, he: 'שער הניצחון', postHe: 'בן שמונה עשרה, זרועות פרושות באמצע חגיגה על המגרש למרגלות הכרמל, שאר הקבוצה נוהרת פנימה מאחוריו.', en: 'The winning goal', tier: 'minor', post: 'Eighteen, arms flung wide mid-celebration on the pitch below the Carmel, the rest of the team streaming in behind him.' },
        { year: 1982, he: 'מכין את החנות הראשונה', postHe: 'בן עשרים ושבע, צבע על הלחי, מגלגל את המדפים בלבן בחלל הריק שעמד להפוך לחנות כלי העבודה שלו.', en: 'Fitting out the first shop', tier: 'minor', post: 'Twenty-seven, paint across one cheek, rolling the shelves white in the empty storefront that was about to become his hardware shop.' },
        { year: 1990, he: 'מאחורי הדלפק', postHe: 'החנות בשיא תנופתה — מכלי ברגים, מדפים עד התקרה, ודב מנהל טקס מעל הקופה. חצי חיפה בילתה שם בוקר של יום שישי בוויכוח איתו על הבורג הנכון. לכאן נכנס דוד יום אחד בשביל ציר — ויצא עם חבר הכי טוב לכל החיים.', en: 'Behind the counter', tier: 'major', post: 'The shop in full swing — bins of bolts, shelves to the ceiling, and Dov holding court over the register. Half of Haifa spent a Friday morning there arguing with him about the right screw. It was here David wandered in for a hinge one day and left with a best friend for life.' },
        { year: 2026, he: 'סנדק', postHe: 'בן שבעים ואחת, קסקט וזקן לבן, שואג מצחוק עם קטנטן מתולתל מהמשפחה שאימץ לעצמו על הברך. עדיין האיש הכי רועש והכי חם בכל שולחן — והסנדק של חנה עד היום.', en: 'Godfather', tier: 'major', post: 'Seventy-one, flat cap and white beard, roaring with laughter with a small curly-haired one from the family he adopted as his own on his knee. Still the loudest and warmest man at any table — and Hannah’s godfather to this day.' } ],
      bio: { he: 'חברו הקרוב של דוד; סנדק של חנה.', en: "David's closest friend; godfather to Hannah." } },

    // ---- Gen 3 ----
    { id: 'eli',    gen: 3, sex: 'm', name: { en: 'Eli Adler',     he: 'אֵלִי אַדְלֶר' },
      birth: { year: 1990, place: 'Tel Aviv, Israel' }, death: null,
      parents: ['aaron', 'tamar'], milestones: [
        { year: 1992, he: 'תצלום ראשון', postHe: 'בן שנתיים על רצפת הסלון, הלשון בין השיניים, מערים את קוביות העץ גבוה מכפי שמישהו חשב שיגיעו. טלוויזיית סבא והשטיח הטוב — כל הדירה בפריים אחד.', en: 'First photograph', tier: 'minor', post: 'Two years old on the salon floor, tongue between his teeth, stacking the wooden blocks higher than anyone thought they would go. The SABA television and the good rug — the whole apartment in one frame.' },
        { year: 1998, he: 'מגדל הלגו', postHe: 'בן שמונה, בחולצת מיקי מאוס, עומד על המשמר ליד מגדל לגו כמעט בגובהו. זה לקח שלושה ימים ואת כל הקופסה, והוא לא נתן לאיש לנשום לידו.', en: 'The Lego tower', tier: 'minor', post: 'Eight, in the Mickey Mouse shirt, standing guard beside a Lego tower nearly his own height. It took three days and the whole box, and he would not let anyone breathe near it.' },
        { year: 2003, he: 'גיר על חצר בית הספר', postHe: 'בן שלוש עשרה, אוזניות באוזניים, מצייר עיר שלמה בגיר על חצר בית הספר בזמן שכולם משחקים סביבו כדורגל. הבניינים כבר אז היו החלק המעניין.', en: 'Chalk on the schoolyard', tier: 'minor', post: 'Thirteen, headphones in, drawing a whole chalk city across the schoolyard while everyone else played football around him. The buildings were already the interesting part.' },
        { year: 2006, he: 'שנות הסקייטבורד', postHe: 'בן שש עשרה במסדרון בית הספר, הקרש מתחת לזרוע והאייפוד מיני מוצמד — תקופת האינפקטד מאשרום, וראשית העין לקווים ולמבנה.', en: 'Skateboard years', tier: 'minor', post: 'Sixteen in the school corridor, board under his arm and the little iPod mini clipped on — the Infected Mushroom era, and the beginnings of an eye for lines and structure.' },
        { year: 2012, he: 'סיים את האוניברסיטה', postHe: 'אדריכלות, תל אביב. הוצא על כתפי הכיתה כולה, הדיפלומה מורמת כמו טלסקופ. אהרן שמר את התמונה על שולחנו.', en: 'Graduated university', tier: 'minor', post: 'Architecture, Tel Aviv. Carried out on the shoulders of the whole class, diploma held up like a telescope. Aaron kept the photo on his desk.' },
        { year: 2016, he: 'באתר הבנייה', postHe: 'בן עשרים ושש, קסדה על הראש, הפרויקט הראשון שלו מתחת לפיגומים — מסביר לכל מי שמוכן להקשיב איפה בדיוק הקורה אמורה לעבור.', en: 'On the building site', tier: 'minor', post: 'Twenty-six, hard hat on, first project of his own under the scaffolding — explaining to anyone who would listen exactly where the beam was supposed to go.' },
        { year: 2026, he: 'סטודיו משלו', postHe: 'מאחורי שולחן עמוס מודלים מקלקר ושרטוטים נעוצים — משרד משלו, עשר שנים בהקמה.', en: 'His own studio', tier: 'minor', post: 'Behind a desk crowded with foam models and pinned-up drawings — a practice of his own, ten years in the making.' } ],
      bio: { he: 'בנם של אהרן ותמר.', en: 'Son of Aaron & Tamar.' } },
    { id: 'maya',   gen: 3, sex: 'f', name: { en: 'Maya Adler',    he: 'מַעְיָן אַדְלֶר' },
      birth: { year: 1994, place: 'Tel Aviv, Israel' }, death: null,
      parents: ['aaron', 'tamar'], milestones: [
        { year: 1996, he: 'תצלום ראשון', postHe: 'עוד לא בת שנתיים, בכיסא האוכל עם סינר הבמבה, ספגטי בשיער ושתי ידיים באוויר — מאושרת מכל הבלגן. תמר בדיוק מחוץ לפריים, מוכנה עם המגבת.', en: 'First photograph', tier: 'minor', post: 'Not quite two, in the high chair with the Bamba bib, spaghetti in her hair and both hands in the air \u2014 delighted with the whole mess. Tamar just out of frame, ready with the towel.' },
        { year: 2002, he: 'יריד המדע', postHe: 'שנת הר הגעש מסודה לשתייה, תג שם על החולצה המפוספסת, מחכה לתורה להציג בזמן שניסוי של מישהו אחר מתפוצץ בנצנצים מאחוריה. הסימן הראשון למדענית.', en: 'The science fair', tier: 'minor', post: 'The baking-soda volcano year, name tag on her striped shirt, waiting her turn to present while someone else\u2019s experiment went off in glitter behind her. The first sign of the scientist.' },
        { year: 2010, he: 'לומדת ליד שולחן המטבח', postHe: 'בת שש עשרה, סנטר על היד ליד שולחן המטבח עם הקלסר פתוח והבמבה בהישג יד, סבתא מבשלת מאחוריה. שם קרתה רוב שנת הבגרויות.', en: 'Studying at the kitchen table', tier: 'minor', post: 'Sixteen, chin on her hand at the kitchen table with the folder open and the Bamba within reach, Savta cooking behind her. This was where most of the matriculation year happened.' },
        { year: 2019, he: 'עברה ללמוד רפואה בחו״ל', postHe: 'בת עשרים וחמש, צווארון המעיל מורם נגד עיר חדשה וקרה — התמונה הראשונה ששלחה הביתה אחרי שנסעה ללימודי רפואה. תמר החזיקה אותה על המקרר שנים.', en: 'Moved abroad to study medicine', tier: 'major', post: 'Twenty-five, coat collar up against a cold new city \u2014 the first photo she sent home after leaving for medical school. Tamar kept it on the fridge for years.' },
        { year: 2020, he: 'שנה ראשונה במחלקות', postHe: 'סקרבס מתחת לז׳קט מושאל, העייפות כבר מציצה מעט סביב העיניים — וגם הרוגע שיעשה אותה טובה בזה, כבר שם.', en: 'First year on the wards', tier: 'minor', post: 'Scrubs under a borrowed jacket, the tiredness already showing a little around the eyes \u2014 and the calm that would make her good at this already there too.' },
        { year: 2026, he: 'רופאה, סוף סוף', postHe: 'במחלקה בסוף משמרת ארוכה, חלוק לבן וסטטוסקופ, הקפה מתקרר לה ביד. דודה-רבתא שרה, שעזרה לגדל אותה, סיפרה לכל מי שהסכים להקשיב.', en: 'A doctor at last', tier: 'major', post: 'On the ward at the end of a long shift, white coat and stethoscope, coffee going cold in her hand. Great-aunt Sarah, who helped raise her, told anyone who\u2019d listen.' } ],
      bio: { he: 'בתם של אהרן ותמר. גדלה בחלקה אצל דודתה-רבתא שרה.', en: 'Daughter of Aaron & Tamar. Raised in part by her great-aunt Sarah.' } },
    { id: 'hannah', gen: 3, sex: 'f', name: { en: 'Hannah Friedman', he: 'חַנָּה פְרִידְמַן' },
      birth: { year: 1991, place: 'Haifa, Israel' }, death: null,
      parents: ['leah', 'michael'], milestones: [
        { year: 1993, he: 'תצלום ראשון', postHe: 'עוד לא בת שנתיים, יושבת בסל הלחם על ספסל המאפייה בין הכיכרות הטריות, קמח על שתי הידיים. היא כמעט גדלה בחדר הזה.', en: 'First photograph', tier: 'minor', post: 'Not quite two, sitting in the bread basket on the bakery bench among the fresh loaves, flour on both hands. She practically grew up in that room.' },
        { year: 1999, he: 'אופה עם סבא דוד', postHe: 'בת שמונה בסינר הכחול, מראה לסבא דוד את החלה הקטנה שקלעה בעצמה. הוא שמר על מחמצת המשפחה, והיא לא זזה מצידו בימי אפייה.', en: 'Baking with Saba David', tier: 'minor', post: 'Eight years old in the blue smock, showing her grandfather David the little challah she had shaped herself. He kept the family starter going, and she never left his side on baking days.' },
        { year: 2004, he: 'שיעורי בית על ספסל המאפייה', postHe: 'בת שלוש עשרה, מכינה שיעורים על משטח השיש בין המגשים, עיפרון בין השיניים — צנצנת המחמצת של לאה (מסומנת „מרץ 1978”) תמיד בהישג יד.', en: 'Homework at the bakery bench', tier: 'minor', post: 'Thirteen, doing her homework on the marble slab between the trays, pencil in her teeth \u2014 the jar of Leah\u2019s starter (marked \u201cMarch 1978\u201d) always within reach.' },
        { year: 2007, he: 'הכיכר הראשונה שלה', postHe: 'בת שש עשרה, בנדנה אדומה וסינר, מרימה את מחמצת הלחם הראשונה שאפתה מההתחלה ועד הסוף. המחמצת של לאה מ-1978 עשתה את העבודה, אבל העיצוב כולו שלה.', en: 'Her first proper loaf', tier: 'major', post: 'Sixteen, red bandana and apron, holding up the first sourdough she baked start to finish. Leah\u2019s 1978 starter did the work, but the shaping was all hers.' },
        { year: 2017, he: 'לחם מחמצת של חנה בשוק', postHe: 'בת עשרים ושש, דוכן שוק משלה — „לחם מחמצת של חנה” — בנוי על מחמצת המשפחה שאמה החזיקה בחיים מאז 1970. נמכר עד הסוף כמעט כל בוקר.', en: 'Hannah\u2019s Sourdough at the shuk', tier: 'major', post: 'Twenty-six, her own market stall \u2014 \u201cלחם מחמצת של חנה, Hannah\u2019s Sourdough\u201d \u2014 built on the family starter her mother kept alive since 1970. It sold out most mornings.' },
        { year: 2026, he: 'נושאת את המחמצת הלאה', postHe: 'בת שלושים וחמש, חורצת כיכר במאפייה שלה, אותה צנצנת „1970 — המחמצת של לאה” על המדף מאחוריה. ארבעה דורות של לחם, עדיין תופח.', en: 'Carrying the starter forward', tier: 'minor', post: 'Thirty-five, scoring a loaf in her own bakery, the same \u201c1970 \u2014 Leah\u2019s Sourdough\u201d jar on the shelf behind her. Four generations of bread, still rising.' } ],
      bio: { he: 'בתם של לאה ומיכאל. שומרת מחמצת המשפחה ומסורת המאפייה שהחלה סבתא-רבתא מרים.', en: 'Daughter of Leah & Michael. Keeper of the family sourdough starter and the bakery tradition begun by her great-grandmother Miriam.' } },
    { id: 'benjamin', gen: 3, sex: 'm', name: { en: 'Benjamin Friedman', he: 'בִּנְיָמִין פְרִידְמַן' },
      birth: { year: 1995, place: 'Haifa, Israel' }, death: null,
      parents: ['leah', 'michael'], milestones: [
        { year: 1997, he: 'תצלום ראשון', postHe: 'בן שנתיים וישן עמוק בתוך הכביסה החמה שיצאה הרגע מהמייבש — גרב אחת חצי יורדת, האמבולנס-צעצוע נטוש על הרצפה. לאה השאירה אותו שם והלכה להביא את המצלמה.', en: 'First photograph', tier: 'minor', post: 'Two years old and fast asleep in the warm laundry straight out of the dryer \u2014 one sock half off, the toy ambulance abandoned on the floor. Leah left him there and fetched the camera instead.' },
        { year: 2003, he: 'המלחם', postHe: 'בן שמונה, בחולצת הרובוט, קצה הלשון בחוץ, מלחים ערכה על שולחן המטבח מעל עיתון פרוש — הידיים של סבא-רבא יוסף, שלושה דורות אחר כך.', en: 'The soldering iron', tier: 'minor', post: 'Eight, in the robot t-shirt, tip of the tongue out, soldering a kit at the kitchen table over spread newspaper \u2014 great-grandfather Yosef\u2019s hands, three generations on.' },
        { year: 2008, he: 'תחפושת המכונה', postHe: 'בן שלוש עשרה — מסננת בתור קסדה, לוח בקרה מקרטון מכוסה חוגות מצוירות ביד, זרועות מונפות בניצחון. הוא חיווט לתוכה זמזם אמיתי שאיש לא הצליח לכבות שבוע.', en: 'The machine costume', tier: 'minor', post: 'Thirteen \u2014 a colander for a helmet, a cardboard console covered in hand-drawn dials, arms up in triumph. He\u2019d wired an actual buzzer into it that nobody could switch off for a week.' },
        { year: 2011, he: 'שנות המריו', postHe: 'בן שש עשרה, גשר בשיניים וחולצת מריו מפוקסלת, באמצע צחוק על הספה הפרחונית עם השלט — הטלוויזיה הקטנה מריצה את המשחק שהוא משחק מאז לפני שידע לקרוא.', en: 'The Mario years', tier: 'minor', post: 'Sixteen, braces and a pixel-Mario shirt, mid-laugh on the flowered sofa with the controller \u2014 the little CRT running the game he\u2019d played since before he could read.' },
        { year: 2021, he: 'עבודה ראשונה במפרץ', postHe: 'בן עשרים ושש, תג ושרוך, מפרץ חיפה זוהר מאחוריו — היום הראשון בעבודת ההייטק שאליה כיוון עוד מימי המלחם.', en: 'First job in the bay', tier: 'major', post: 'Twenty-six, lanyard and badge, the Haifa bay glowing behind him \u2014 the first day at the tech job he\u2019d aimed at since the soldering-iron days.' },
        { year: 2026, he: 'בית על הכרמל', postHe: 'בן שלושים ואחת, תרמיל על הגב, מציג את המפרץ כולו מרכס הכרמל בשעת הזהב — העיר שמעולם לא ממש רצה לעזוב.', en: 'Home on the Carmel', tier: 'minor', post: 'Thirty-one, pack on, showing off the whole bay from the Carmel ridge at golden hour \u2014 the city he never quite wanted to leave.' } ],
      bio: { he: 'בנם של לאה ומיכאל.', en: 'Son of Leah & Michael.' } },
    { id: 'tal',    gen: 3, sex: 'f', name: { en: 'Tal Adler',     he: 'טַל אַדְלֶר' },
      birth: { year: 2009, place: 'Tel Aviv, Israel' }, death: null,
      parents: ['daniel', 'noa'], milestones: [
        { year: 2011, he: 'תצלום ראשון', postHe: 'בת שנתיים ומכוסה בצבעי פנדה מהראש ועד הידיים — ירוק במעלה הזרועות, אדום על העיתון — מחייכת כאילו התחמקה מעונש. דניאל, הצלם של המשפחה, לא הצליח להפסיק לצחוק מספיק זמן כדי לנזוף בה.', en: 'First photograph', tier: 'minor', post: 'Two years old and covered head to hand in crayon \u2014 green up the arms, red across the newspaper \u2014 grinning like she\u2019d gotten away with something. Daniel, the family photographer, could not stop laughing long enough to tell her off.' },
        { year: 2018, he: 'תמיד יוצרת משהו', postHe: 'בת תשע, קבורה בכריות על הספה הגדולה עם ספר וצבע שעוד על הידיים מאחר הצהריים — תמיד היה צבע על הידיים.', en: 'Always making something', tier: 'minor', post: 'Nine, buried in cushions on the big couch with a book and paint still on her hands from the afternoon \u2014 there was always paint on her hands.' },
        { year: 2021, he: 'ציור הקיר מקרטון', postHe: 'בת שתים עשרה, שתי מכחולים ומבט שמעז אותך להעיר, כל רצפת החדר שלה הפכה לפרויקט ציור באביב ארוך אחד של בית.', en: 'The cardboard mural', tier: 'minor', post: 'Twelve, two brushes and a look that dared you to comment, the whole floor of her room turned into a painting project during a long stay-home spring.' },
        { year: 2026, he: 'סקצ׳בוק תמיד פתוח', postHe: 'בת שבע עשרה, פוסטרים של להקות ואורות פיות, ציפורניים מנוקדות צבע וסקצ׳בוק פתוח על הברך — נתפסה באמצע חלום בהקיץ, כבר במקום אחר.', en: 'Sketchbook always open', tier: 'minor', post: 'Seventeen, band posters and fairy lights, paint-flecked nails and a sketchbook open on her knee \u2014 caught mid-daydream, already somewhere else.' } ],
      bio: { he: 'בתם של דניאל ונועה.', en: 'Daughter of Daniel & Noa.' } },

    // Gen 3 spouse (married in)
    { id: 'dana',   gen: 3, sex: 'f', name: { en: 'Dana Adler',  he: 'דָּנָה אַדְלֶר' },
      names: { birth: { en: 'Dana Shapiro', he: 'דָּנָה שַׁפִּירוֹ' } },
      nameChange: { year: 2017, kind: 'marriage', from: 'Shapiro', to: 'Adler',
        note: 'Born Dana Shapiro; took the Adler name when she and Eli married in 2017.' },
      birth: { year: 1992, place: 'Tel Aviv, Israel' }, death: null, parents: [], milestones: [
        { year: 1994, he: 'קיץ ראשון בים', postHe: 'עוד לא בת שנתיים, בכובע שמש רחב ובבגד ים מפוספס, פוגשת את הים התיכון בפעם הראשונה — שתי הידיים טפוחות על החול הרטוב במקום שאליו מגיעים הגלים. לא בכתה אף פעם; רק המשיכה להושיט יד אל הגל הבא.', en: 'First summer at the sea', tier: 'minor', post: 'Not quite two, in a floppy sun hat and a striped bathing suit, meeting the Mediterranean for the first time \u2014 both hands slapped flat on the wet sand where the waves came in. She never once cried; she just kept reaching for the next wave.' },
        { year: 2000, he: 'מעבר לקצה', postHe: 'בת שמונה בבריכה השכונתית, זרועות פרושות וערימת צמידי חברות על כל פרק יד, נתפסה בחצי השנייה שלפני ההתזה. קודם היא דאגה שכולם יעצרו ויסתכלו.', en: 'Off the edge', tier: 'minor', post: 'Eight years old at the neighbourhood pool, arms flung wide and a stack of friendship bracelets up each wrist, caught in the half-second before the splash. She had made everyone stop and watch first.' },
        { year: 2004, he: 'גלגלונים בפארק', postHe: 'בת שתים עשרה, הפוכה בפארק בשעת הזהב, סנדלי נצנצים מכוונים לשמיים וחיוך שמצא את המצלמה באמצע גלגלון. הברכיים השרוטות היו עניין של כבוד.', en: 'Cartwheels in the park', tier: 'minor', post: 'Twelve, upside down in the park at golden hour, glitter sandals pointed at the sky and a grin that found the camera mid-cartwheel. The scraped knees were a point of pride.' },
        { year: 2008, he: 'בת שש עשרה, על החול התל אביבי', postHe: 'בת שש עשרה, ברכיים אסופות בתוך קפוצ׳ון ענק על החוף כשהעיר נדלקת מאחוריה והשמש שוקעת מעל המים. זה היה הקיץ שבו היא וחברותיה כמעט גרו על רצועת החול ההיא.', en: 'Sixteen, on the Tel Aviv sand', tier: 'minor', post: 'Sixteen, knees pulled up inside an oversized hoodie on the beach as the city lit up behind her and the sun went down over the water. That was the summer she and her friends practically lived on that stretch of sand.' },
        { year: 2019, he: 'שולחן שבת משלה', postHe: 'בת עשרים ושבע, מדליקה נרות בשולחן ארוך מקושט אורות בגינה — בית משלה עכשיו, וקהל שלם של חברים ומשפחה מחכה לברכה. שנתיים בתוך משפחת אדלר, והיא אימצה את האירוח כאילו עשתה זאת מאז ומעולם.', en: 'Her own Shabbat table', tier: 'major', post: 'Twenty-seven, lighting the candles at a long table strung with lights in the garden \u2014 her own home now, a whole crowd of friends and family waiting on the blessing. Two years into the Adler family, and she had taken to hosting as though she had always done it.' },
        { year: 2026, he: 'אופה עם יונתן', postHe: 'בת שלושים וארבע, קמח על כל הדלפק ויונתן על המותן, שניהם מערבבים משהו שאולי יהיה לחם ואולי לא. הוא מתעניין הרבה יותר בכף העץ; היא לא הייתה רוצה את זה אחרת.', en: 'Baking with Yonatan', tier: 'minor', post: 'Thirty-four, flour across the counter and Yonatan on her hip, the two of them mixing something that may or may not become bread. He is far more interested in the wooden spoon; she would not have it any other way.' } ],
      bio: { he: 'אשתו של אלי. לבית שפירו; קיבלה את השם אדלר כשנישאו ב-2017.', en: "Eli's wife. Born Dana Shapiro; took the Adler name when they married in 2017." } },

    // ---- Gen 4 ----
    { id: 'yonatan',gen: 4, sex: 'm', name: { en: 'Yonatan Adler', he: 'יוֹנָתָן אַדְלֶר' },
      birth: { year: 2019, place: 'Tel Aviv, Israel' }, death: null,
      parents: ['eli', 'dana'], milestones: [
        { year: 2020, he: 'תצלום ראשון', postHe: 'עוד לא בן שנה, ישן עמוק על כתפו של אלי באור האחרון של אחר הצהריים, אגרוף קטן אוחז בפלנל. הוא נלחם בשנת הצהריים שעה שלמה ואז הפסיד אותה בבת אחת.', en: 'First photograph', tier: 'minor', post: 'Not quite one, fast asleep on Eli\u2019s shoulder in the last of the afternoon light, one small fist gripping the flannel. He had fought the nap for a full hour and then lost it all at once.' },
        { year: 2026, he: 'שעון הכיס', postHe: 'בן שבע במרפסת, מצמיד לאוזנו את שעון הכיס מפליז של סבא-רבא-רבא יוסף כדי לשמוע אותו מתקתק — אותו שעון שהגיע מווילנה ב-1934. הוא קרוי על שם יוסף, ושרה נתנה לו להחזיק אותו בדיוק בשביל התצלום הזה.', en: 'The pocket-watch', tier: 'major', post: 'Seven years old on the balcony, holding great-great-grandfather Yosef\u2019s brass pocket-watch to his ear to catch it ticking \u2014 the same watch that came from Vilnius in 1934. He is named for Yosef, and Sarah let him hold it for exactly this photograph.' } ],
      bio: { he: 'הצעיר במשפחה. קרוי על שם סבא-רבא-רבא יוסף.', en: 'The youngest. Named for his great-great-grandfather Yosef.' } },
  ];

  // Unions (marriages & partnerships). a/b are person ids. order = layout order of the spouse relative to focal (not critical).
  const unions = [
    { id: 'u_yosef_miriam', a: 'yosef',  b: 'miriam', year: 1929, type: 'marriage' },
    { id: 'u_david_rivka',  a: 'rivka',  b: 'david',  year: 1958, type: 'marriage', endYear: 1968, endReason: 'death' },
    { id: 'u_david_rachel', a: 'david',  b: 'rachel', year: 1971, type: 'marriage' },
    { id: 'u_aaron_tamar',  a: 'aaron',  b: 'tamar',  year: 1987, type: 'marriage' },
    { id: 'u_leah_michael', a: 'leah',   b: 'michael',year: 1989, type: 'marriage' },
    { id: 'u_daniel_noa',   a: 'daniel', b: 'noa',    year: 2004, type: 'partnership' },
    { id: 'u_eli_dana',     a: 'eli',    b: 'dana',   year: 2017, type: 'marriage', postHe: 'שרשרת אורות מעל החצר, דנה מסדרת לו את השיער באמצע ריקוד. איש לא זוכר שהלהקה הפסיקה לנגן.', post: 'String lights over the courtyard, Dana fixing his hair mid-dance. Nobody remembers the band ever stopping.' },
  ];

  // Side-links — non-blood ties. kind is a free label.
  const sideLinks = [
    { from: 'moshe',  to: 'david',  kind: 'Raised him', detail: 'The neighbour who raised me' },
    { from: 'dov',    to: 'hannah', kind: 'Godfather' },
    { from: 'sarah',  to: 'maya',   kind: 'Like a mother', detail: 'Helped raise her' },
  ];

  window.FAMILY = { people, unions, sideLinks };
})();
